function [structEEG, lst_changes] = f_ica(structEEG)

[structEEG, lst_changes] = pop_runica(structEEG, ...
    'icatype', 'runica', ...
    'extended', 1, ...
    'interrupt', 'off', ...
    'chanind', find(~strcmp({structEEG.chanlocs.description}, 'Noisy')));
% chanind are the channel indices to INCLUDE (reverse strcmp)

[structEEG, lst_changes{end+1,1}] = eeg_checkset( structEEG );

end