[EEG, lst_changes{end+1,1}] = pop_runica(EEG, ...
    'icatype', 'runica', ...
    'extended', 1, ...
    'interrupt', 'off', ...
    'chanind', find(~strcmp({EEG.chanlocs.description}, 'Noisy')));
% chanind are the channel indices to INCLUDE (reverse strcmp)

[EEG, lst_changes{end+1,1}] = eeg_checkset( EEG );