EEG2 = EEG;

get_cidx= {EEG.event.mffkey_cidx};

Placebo_Epochs = find(mod(str2double(get_cidx),2)==0);
Odor_Epochs = find(mod(str2double(get_cidx),2)~= 0);

[EEG, lst_changes{end+1,1}] = pop_select( EEG, 'trial', Placebo_Epochs );

[EEG, lst_changes{end+1,1}] = pop_epoch( EEG, ...
    {  'DIN1'  }, ...
    [-15  15], ...
    'newname', 'temp_set', ...
    'epochinfo', 'yes'); % or DIN2 for Off-On organization

[EEG, lst_changes{end+1,1}] = pop_saveset( EEG, ...
    'filename', str_savefile, ...
    'filepath', savePath);

% ------
EEG = EEG2;

[EEG, lst_changes{end+1,1}] = pop_select( EEG, 'trial', Odor_Epochs );

[EEG, lst_changes{end+1,1}] = pop_epoch( EEG, ...
    {  'DIN1'  }, ...
    [-15  15], ...
    'newname', 'temp_set', ...
    'epochinfo', 'yes'); % or DIN2 for Off-On organization

[EEG, lst_changes{end+1,1}] = pop_saveset( EEG, ...
    'filename', str_savefile, ...
    'filepath', savePath);